services:

    nextjs-app:
       container_name: nextjs-app
       build:
          context: .
          dockerfile: Dockerfile
       ports:
          - "3000:3000"
       command:
          "npm run start" #for production environment 
       environment:
          - AUTH_TRUST_HOST=http://192.168.0.102:3000

